#!/usr/bin/env python3
"""Regenerates assets/ for the architecture dossier from its real sources.

Run from this directory: python3 prepare_assets.py

What's reproducible from files already in this repo:
  - fig-scenetree.png / fig-uml.png  <- rendered here from diagrams/*.dot
    (Graphviz; `dot` must be on PATH)
  - fig-controls.png                 <- copied straight from the game's own
    help illustration (assets/graphics/help/keyboard.png)
  - galaga-icon.png                  <- copied from the app's own launcher
    icon (galaga-icon 432x432.png in the project root)

What ISN'T reproducible by this script (kept only as the already-processed
files already sitting in assets/ — this script leaves them alone):
  - fig-formation.jpg / fig-collision.jpg — real screenshots captured live
    off an Anbernic RG552 over adb (title -> Play -> a formation fly-in, and
    a near-collision moment) during the 2026-09-16 session, then downscaled
    to <=1300px wide / JPEG q82 to keep the standalone export a reasonable
    size. Recapturing them needs the actual device connected; there's
    nothing to "run" here.
"""

import shutil
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
GALAGA_ROOT = HERE.parent.parent
ASSETS = HERE / "assets"
DIAGRAMS = HERE / "diagrams"

ASSETS.mkdir(exist_ok=True)


def render_diagram(dot_file: Path, out_file: Path, dpi: int = 150) -> None:
    subprocess.run(
        ["dot", "-Tpng", f"-Gdpi={dpi}", str(dot_file), "-o", str(out_file)],
        check=True,
    )
    print("rendered", out_file.relative_to(HERE))


def copy_asset(src: Path, dst: Path) -> None:
    shutil.copyfile(src, dst)
    print("copied", dst.relative_to(HERE), "<-", src)


def main() -> None:
    render_diagram(DIAGRAMS / "scenetree.dot", ASSETS / "fig-scenetree.png")
    render_diagram(DIAGRAMS / "uml.dot", ASSETS / "fig-uml.png")

    copy_asset(
        GALAGA_ROOT / "assets" / "graphics" / "help" / "keyboard.png",
        ASSETS / "fig-controls.png",
    )
    copy_asset(
        GALAGA_ROOT / "galaga-icon 432x432.png",
        ASSETS / "galaga-icon.png",
    )

    print(
        "\nfig-formation.jpg / fig-collision.jpg left untouched — "
        "real device screenshots, not regenerated by this script (see "
        "the module docstring)."
    )


if __name__ == "__main__":
    main()
